### ISSUE TITLE
Linux studio build 0.8.4 crashes on startup

### ISSUE THREAD

**Issue by lukedodd** [harfang3d/harfang3d#54]
Linux studio build 0.8.4 crashes on startup.

(From here: https://github.com/harfang3d/harfang3d/releases/download/v3.2.6/studio-0.8.4-ubuntu64.zip).

Splash screen briefly displays then it disappears, no console output.

Previous version runs fine on this machine. Ubuntu 22.04. Replicate on another Ubuntu 22.04 machine. nvidia gpu.

I tried a little debugging in gdb:

```
gdb ./studio 
GNU gdb (Ubuntu 12.0.90-0ubuntu1) 12.0.90
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./studio...
(No debugging symbols found in ./studio)
(gdb) set follow-fork-mode child
(gdb) break exit
Breakpoint 1 at 0x5c4d0 (2 locations)
(gdb) break abort
Breakpoint 2 at 0x5c770
(gdb) break _exit
Breakpoint 3 at 0x5d320
(gdb) start
Temporary breakpoint 4 at 0xaea20
Starting program: /home/luke/harfang/studio/studio-0.8.4-ubuntu64/studio 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Temporary breakpoint 4, 0x0000555555602a20 in main ()
(gdb) continue
Continuing.
[Attaching after Thread 0x7ffff57fcac0 (LWP 332375) fork to child process 332381]
[New inferior 2 (process 332381)]
[Detaching after fork from parent process 332375]
[Inferior 1 (process 332375) detached]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
process 332381 is executing new program: /usr/bin/dash
Error in re-setting breakpoint 1: Function "exit" not defined.
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[Attaching after Thread 0x7ffff7d6b740 (LWP 332381) vfork to child process 332384]
[New inferior 3 (process 332384)]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[Switching to Thread 0x7ffff7d6b740 (LWP 332384)]

Thread 3.1 "sh" hit Breakpoint 3, __GI__exit (status=126) at ../sysdeps/unix/sysv/linux/_exit.c:27
27      ../sysdeps/unix/sysv/linux/_exit.c: No such file or directory.
(gdb) bt
#0  __GI__exit (status=126) at ../sysdeps/unix/sysv/linux/_exit.c:27
#1  0x000055555555956f in ?? ()
#2  0x000055555556b740 in ?? ()
#3  0x000055555555cc25 in ?? ()
#4  0x000055555555d8de in ?? ()
#5  0x00005555555673ac in ?? ()
#6  0x0000555555560c00 in ?? ()
#7  0x0000555555560c00 in ?? ()
#8  0x00005555555646c2 in ?? ()
#9  0x0000555555558d36 in ?? ()
#10 0x00007ffff7d97d90 in __libc_start_call_main (main=main@entry=0x555555558ae0, argc=argc@entry=3, argv=argv@entry=0x7fffffffdcc8) at ../sysdeps/nptl/libc_start_call_main.h:58
#11 0x00007ffff7d97e40 in __libc_start_main_impl (main=0x555555558ae0, argc=3, argv=0x7fffffffdcc8, init=<optimised out>, fini=<optimised out>, rtld_fini=<optimised out>, stack_end=0x7fffffffdcb8) at ../csu/libc-start.c:392
#12 0x0000555555558f15 in ?? ()
(gdb) list
22      in ../sysdeps/unix/sysv/linux/_exit.c
(gdb) continue
Continuing.
[Detaching vfork parent process 332381 after child exit]
[Inferior 2 (process 332381) detached]
[Inferior 3 (process 332384) exited with code 0176]
(gdb) 
quit
```

**Comment by astrofra** [comment]
Hi !
This is unfortunate. Thanks for reporting the issue, we will look into it.
At first glance it could be related to a recent change in the way we handle the asset compiler while Studio is running, but we of course need to investigate.
